
name: Build and deploy ASP.Net Core app to Azure Web App - sndotnetapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
      contents: read
      id-token: write
env:
  PROJECT: sndotnetwinapp

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production



    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o publish_output

      - name: Create Zip Package
        run: |
          cd publish_output
          zip -r ../${{ env.PROJECT }}.zip .
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT }}-zip
          path: ${{ env.PROJECT }}.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.PROJECT }}-zip
          path: .

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      #- name: Stop Azure Web App
      #  run: az webapp stop --name ${{ env.PROJECT }} --resource-group Snambissan

      #- name: Wait for 50 seconds after stopping app
      #  run: sleep 50

      - name: Deploy to Azure App Service
        run: |
          az webapp deployment source config-zip \
            --name ${{ env.PROJECT }} \
            --resource-group Snambissan \
            --src "${{ env.PROJECT }}.zip"

      #- name: Start Azure Web App
      #  run: az webapp start --name ${{ env.PROJECT }} --resource-group Snambissan
